version: '3.7'
services:
    db:
        image: mysql:5.7.16
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ''
        ports:
            - 3307:3306
        volumes:
            - ./db:/var/lib/mysql
        networks:
            internal-network:
                aliases:
                    - db-host
    app:
        build:
            context: ./app
            dockerfile: ../Dockerfile
        image: 'laravel_app'
        container_name: laravel-app
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./app:/var/www/html
        networks:
            internal-network:
                aliases:
                    - app-host
networks:
    internal-network:
        name: inter-network
        driver: bridge
